### ISSUE TITLE
Recipient name not aligned with rest of address

### ISSUE THREAD

**Issue by ddffnn** [null93/envelopes#1]
When left alignment is enabled, the first line is still centered. I don't think this is intentional:

![image](https://github.com/null93/envelopes/assets/9387818/fbce58bb-caa9-4600-b4af-565ed4bf658b)

**Comment by null93** [comment]
@ddffnn Good catch! Thanks for opening the issue. Fixed this in 63c6c26046b0f19d408ec2e2068ab4c649336086.
